Readme updates
PagerNation/Escalator-API pull request #89
Opened 2017-04-13 19:47 UTC by jarrydlee

The initial changes.

Still need to do the sample requests

2017-04-15 23:22 UTC, jarrydlee commented
Added in some steps to create the initial admin user and initial group

2017-04-17 22:39 UTC, kalebingerick requested changes
The set up portion is great, if that's all this PR is then once the few comments I have are addressed it should be good to go.

I would like to see more information in the Running, Tests, and Seeding sections, but those could be updated in another PR

2017-04-17 22:39 UTC, kalebdavis commented on README.md
> +Get the id andtoken returned with the new user object, we will need it in future steps.
space between 'andtoken'

2017-04-17 22:39 UTC, kalebdavis commented on README.md
> +POST - localhost:3000/api/v1/group
Same note as above: This might be more readable if it's also in the code block

2017-04-17 22:39 UTC, kalebdavis commented on README.md
> +This user will need to be made the initial system admin in order to have full permissions. To do this, you will need to access to DB and change the `isSystemAdmin` flag on this user to `true`.
`isSysAdmin` not `isSystemAdmin`

2023-07-13 00:11 UTC, closed without merging